# Generated by Django 5.2.8 on 2025-11-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_cartitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
