# Generated by Django 5.2.8 on 2025-11-17 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='address_1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='address_2',
            new_name='address_line_2',
        ),
    ]
